# Portfolio Optimization API Request Template
portfolio:
  id: "{{PORTFOLIO_ID}}"
  type: "ACCOUNT_CODE"

benchmark:
  id: "{{BENCHMARK_ID}}"
  type: "INDEX_TICKER"

tradeUniverse:
  - instrumentSource:
      id: "{{BENCHMARK_ID}}"
      type: "INDEX_TICKER"
    tradingRule: "BUY_AND_SELL"

task:
  goals:
    - fieldCode: "active_share"
      fieldType: "GOAL_CODE"
      action: "MINIMIZE"
      tradeoff: 1.0
      relativeTo: "BENCHMARK"
  
  portfolioConstraints:
    - fieldCode: "weight"
      fieldType: "CONSTRAINT_CODE"
      minThreshold: "{{SECTOR_WEIGHT_MIN_THRESHOLD}}"
      maxThreshold: "{{SECTOR_WEIGHT_MAX_THRESHOLD}}"
      relativeTo: "BENCHMARK"
      classificationNode:
        classificationName: "GICS Sector"
        levels: ["All"]
    
    - fieldCode: "weight"
      fieldType: "CONSTRAINT_CODE"
      minThreshold: "{{COUNTRY_WEIGHT_MIN_THRESHOLD}}"
      maxThreshold: "{{COUNTRY_WEIGHT_MAX_THRESHOLD}}"
      relativeTo: "BENCHMARK"
      classificationNode:
        classificationName: "Country of Domicile"
        levels: ["All"]
    
    # ... other constraints with placeholders
  
  instrumentConstraints:
    - scope:
        instrumentUniqueId: "{{CASH_INSTRUMENT_ID}}"  # IX244867-0
      units: "PERCENT"
      relativeTo: "NONE"
      fields:
        - fieldCode: "MIN_WEIGHT"
          valueOrField:
            value: 0.0
        - fieldCode: "MAX_WEIGHT"
          valueOrField:
            value: "{{MAX_CASH_WEIGHT}}"
    
    - scope:
        portfolioLevel: "INSTRUMENT_UNIVERSE"
      units: "POSITIONS"
      relativeTo: "NONE"
      fields:
        - fieldCode: "MIN_WEIGHT"
          valueOrField:
            value: 0.0
        - fieldCode: "MIN_TRADE"
          valueOrField:
            value: "{{MIN_LOTS}}"
        - fieldCode: "LOT_INCREMENT"
          valueOrField:
            value: "{{ROUND_LOTS}}"
    
    - scope:
        portfolioLevel: "INSTRUMENT_UNIVERSE"
      units: "VALUE"
      relativeTo: "NONE"
      fields:
        - fieldCode: "MIN_TRADE"
          valueOrField:
            value: "{{VALUE_LOTS}}"

  riskOptions:
    riskModel: "GLOBAL_EQUITY"
    riskModelScaling: "YEAR"
    riskModelHorizon: "QUARTERLY"
  
  options:
    longPositionOnly: true
    longShortCrossOver: true
    benchmarkCrossOver: true
    tradeLevel: "SECURITY"

asOfDate: "{{AS_OF_DATE}}"
reportingCurrency: "{{REPORTING_CURRENCY}}"
saveTo: "TEMPORARY_PORTFOLIO"
enableLookThrough: true
